version: '3.8'
services:
  kmserver:
    build: kmserver/
    container_name: km-server
    ports:
      - "5001:443"
      - "5000:80"
    volumes:
      - "~/dev/km-server/data:/app/logs"
  km-mongodb:
    build: database/
    container_name: km-mongodb
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - "~/dev/km-mongodb/data:/data/db"
  kmfrontend:
    build: front_end/
    container_name: km-frontend
    environment:
      #- REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.81
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"